# SimpleCov configuration. The `SimpleCov.start` call lives in
# spec/rails_helper.rb; this file must stay configuration-only.

SimpleCov.configure do
  load_profile 'rails'

  # Boilerplate base classes generated by Rails, with no logic of our own.
  skip 'app/jobs/application_job.rb'
  skip 'app/mailers/application_mailer.rb'
  skip 'app/channels/application_cable/connection.rb'
  skip 'app/channels/application_cable/channel.rb'
  skip 'app/models/application_record.rb'
end
