# SimpleCov configuration. The `SimpleCov.start` call lives in
# spec/rails_helper.rb; this file must stay configuration-only.

SimpleCov.configure do
  load_profile 'rails'

  enable_coverage :branch

  # The suite covers every line today - keep it that way, otherwise the
  # coverage report is decoration rather than a gate.
  minimum_coverage line: 100, branch: 100

  # Boilerplate base classes generated by Rails, with no logic of our own.
  skip 'app/jobs/application_job.rb'
  skip 'app/mailers/application_mailer.rb'
  skip 'app/channels/application_cable/connection.rb'
  skip 'app/channels/application_cable/channel.rb'
  skip 'app/models/application_record.rb'
end
